---
output:
  pdf_document: default
  html_document: default
---

```{r A}
shoes <- data.frame(ShoeSize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5),
                    Height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0,64.0, 74.5, 67.0, 71.0, 71.0 ))
shoes
```

```{r B.}
Gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M")
Shoes <- cbind(shoes, Gender)
Shoes
```

```{r c.}
mean(ShoeSize)
mean(Height)
```

```{r D.}

```

```{r 2}
Tmonths<-c("March","April","January","November","January","September","October","September","November","August","January","November","November","February","May","August","July","December","August","August","September","November","February", "April")
Tmonths
factor.months<- factor(Tmonths)
factor.months
```

```{r 3.}
summary(Tmonths)
summary(factor.months)
```

```{r 4.}
freq.data<- data.frame(Direction <- c("East", "West", "North"), Frequency<-c(1,4,3))
freq.data
freqDatafactor<-factor(freq.data)
new.order.data <- factor(freqDatafactor, levels= c("East", "West", "North"))
new.order.data
print(new.order.data)
```

```{r 5.}
Excel.import<-read.table(file = 'C:/Users/USER/Documents/worksheet4/import_march', header = TRUE, sep = ',' )
Excel.import
``` 

```{r 6.}
random.num <- sample(1:50, 1)

cat("The chosen number is:", random.num, "\n")

if (random.num == 20) {
  cat("TRUE\n")
} else if (random.num < 1 || random.num > 50) {
  cat("The number selected is beyond the range of 1 to 50\n")
} else {
  cat(random.num, "\n")
}
```

``` {r num7}
#7.
calc.min.bills <- function(price.snack) {
  bill.denom <- c(1000, 500, 200, 100, 50)
  total.bills <- 0
 
  for (bill in bill.denom) {
    num.bills.needed <- price.snack %/% bill
    price.snack <- price.snack %% bill
    total.bills <- total.bills + num.bills.needed
  }
 
  cat("Minimum number of bills needed to purchase the snack:", total.bills, "\n")
}

price.snack <- 1350
calc.min.bills(price.snack)
```

``` {r num8a}
#8.
#a.
students <- data.frame(
  Name = c("Annie" , "Thea", "Steve", "Hanna"),
  Grade1 = c(85,65,75,95),
  Grade2 = c(65,75,55,75),
  Grade3 = c(85,90,80,100),
  Grade4 = c(100,90,85,90)
)
students
```

``` {r num8b}
#b.

students$Average <- (students$Grade1 + students$Grade2 + students$Grade3 + students$Grade4) / 4

for (i in 1:nrow(students)) {
  if (students$Average[i] > 90) {
    cat(students$Name[i], "'The average grade this sem is", students$Average[i], "\n")
  }
}
```

``` {r num8c}
#c
test1_average <- sum(students$Grade1) / nrow(students)
test2_average <- sum(students$Grade2) / nrow(students)
test3_average <- sum(students$Grade3) / nrow(students)
test4_average <- sum(students$Grade4) / nrow(students)

if (test1_average < 80) {
  cat("The 1st test was difficult.\n")
}
if (test2_average < 80) {
  cat("The 2nd test was difficult.\n")
}
if (test3_average < 80) {
  cat("The 3rd test was difficult.\n")
}
if (test4_average < 80) {
  cat("The 4th test was difficult.\n")
}
```

``` {r num8d}
#d.
for (i in 1:nrow(students)) {
  highest_grade <- students$Grade1[i]
  if (students$Grade2[i] > highest_grade) {
    highest_grade <- students$Grade2[i]
  }
  if (students$Grade3[i] > highest_grade) {
    highest_grade <- students$Grade3[i]
  }
  if (students$Grade4[i] > highest_grade) {
    highest_grade <- students$Grade4[i]
  }
  if (highest_grade > 90) {
    cat(students$Name[i], "'s highest grade this semester is", highest_grade, "\n")
  }
}
```


